### ISSUE TITLE
Feature Request: Export In-Hand Item

### ISSUE THREAD

**Issue by d3sknight** [CoolLord22/OtherDrops#10]
Hello Coolord22, thank you a lot for updating this plugin. I got a request
a command which can export in-hand Item to .yml langue would be awesome
since there is a lot of custom item creating nowaday, It's would be useful creating some good loot from OtherDrops

**Comment by CoolLord22** [comment]
This Enhancement has been implemented into the 3.2.5-Beta branch commit: 
https://github.com/CoolLord22/OtherDrops/commit/373cd458db2d5b51b018a3bb85c450534d63da13 Waiting for further testing to ensure it works. For other users interested in the beta releases, please contact me on Discord (or join our [discord](https://discordapp.com/invite/eHBxk5q) server) and check the #Beta-Updates channel. The command that's been added is /od write, with the short form /odw. It will write the item's information to a file inside the OtherDrops plugin folder titled ItemOutput.txt

**Comment by CoolLord22** [comment]
Closing this issue now has the enhancement is officially confirmed to be working in Beta version 3.2.5, added and finalized by commit: 
https://github.com/CoolLord22/OtherDrops/commit/373cd458db2d5b51b018a3bb85c450534d63da13
