### ISSUE TITLE
Support for mine plugins

### ISSUE THREAD

**Issue by Ac3dUd3** [CoolLord22/OtherDrops#102]
**Is your feature request related to a problem? Please describe.**
Can you please add support for block break events, otherdrops used to work with mine plugins.

**Describe the solution you'd like**
I'd like support for JetsPrisonMines on spigot, as currently it overrides the mine and the mine is not registering that people are using it.

**Comment by CoolLord22** [comment]
Block break events haven’t been changed at all, it is more likely that the specific mine plugin you’re using dropped/changed their event listening causing this issue

**Comment by CoolLord22** [comment]
Fixed via the OtherDrops Notifier plugin; download available in #beta-updates channel of Discord.

**Comment by CoolLord22** [comment]
Fixed by using OtherDropsNotifier
