### ISSUE TITLE
Is it possible to add additional XP orbs as drops?

### ISSUE THREAD

**Issue by Jalalien-mc** [CoolLord22/OtherDrops#104]
Hello!

I don't have a problem per se, I'm just wondering if it's possible to add additional XP orbs as drops.  I tried the following:

GUARDIAN:

`            - drop: XP_ORB`
                 `quantity: 100`
                 `chance: 100`

to test if it worked, but nothing appeared to change.  If this isn't possible, no worries at all!

Thanks!

**Comment by CoolLord22** [comment]
I believe using 
`drop: XP@quantity` should work, not 100% sure as I’m not home yet. For further support, if you’re able to, consider joining our Discord server, there’s more users there who can help haha. If not though feel free to comment back here and I’ll respond when I can :)

**Comment by Jalalien-mc** [comment]
Thanks!  I'll try that.

**Comment by CoolLord22** [comment]
Edit: instead of @ I think it’s / so xp/quantity

**Comment by Jalalien-mc** [comment]
Got it

**Comment by Jalalien-mc** [comment]
Ok so just to check, if I want to add 10 xp to a drop, would it look like this:

- drop: XP/10
   chance: 100

or like this:

- drop: XP/QUANTITY
   quantity: 10
   chance: 100

**Comment by Jalalien-mc** [comment]
those dots should be slashes

**Comment by CoolLord22** [comment]
The quantity is already taken into account with the /10 so do either XP/10 or simply drop: XP and then in another line specify quantity

**Comment by Jalalien-mc** [comment]
Ah, k.  Thanks!
