### ISSUE TITLE
TPS drop on PlayerJoinEvent

### ISSUE THREAD

**Issue by xxdamixx** [CoolLord22/OtherDrops#106]
**Description of the problem:** 	

**How to replicate:** 	

	TPS drop on PlayerJoinEvent
**Additional files:** 	
	

https://naimad.xyz/images/opera_lC2oVf6co3.png

https://timings.aikar.co/?id=86c808a3ec1d4befb02a2122a2643c93
check last 15 minutes

**Version Information (please complete the following information):**
 - OS: UBUNTU 18
 - Java Version 8
 - Server Version 1.12.2
 - Plugin Version 3.2.6 Legacy
 
**Checklist**:	
	
- [] I made sure I am using the latest version of OtherDrops	
- [] I made sure I am using a version of Minecraft supported by OtherDrops	
- [] I Made sure the bug/error is not caused by any other plugin	
- [] I included my otherdrops-drops.yml and any relevant includes/changes I made.	
	
**Provide additional information, such as error/debug/ logs. Use http://pastebin.com/ or similar for huge logs.**

**Comment by CoolLord22** [comment]
Hi, not sure what the first screenshot contains, I'm receiving an site couldn't be reached error, but based on the timings report it seems like there was an issue with the update checking. If you'd like, this update checker CAN be disabled in the config, solving your reported TPS drop. However, the beta version (3.2.7) available in our [support discord](discord.gg/eHBxk5q) changes how the update checking is performed, which may further help with performance. 

Let me know if either of these work out, and if you're still experiencing TPS issues I can look into it further!

**Comment by xxdamixx** [comment]
improved after disabling update-checker
thanks
