### ISSUE TITLE
Unbreakable losing dura

### ISSUE THREAD

**Issue by Sweetygamer** [CoolLord22/OtherDrops#108]
Hi ( sry for my english i'm french :/ )
I'm using 1.9 for a custom textures pack (unbreakable+ durability) and when trying the pack i just discovered something strange. When i'm breaking a block with a custom loot, the durability of my unbreakable tool is going down. So you can actually break an unbreakable tool.

1. Give yourself an unbreakable tool
2. Break an otherdrops block
3. The tool lose dura
 - OS: Windows 10
 - Server Version : 1.9.4
 - Plugin Version : last

**Comment by CoolLord22** [comment]
Can you try adding 
`damagetool: 0` 
to the drop? This should make it so that the drop doesn’t damage the tool I believe!

**Comment by Sweetygamer** [comment]
will try it

**Comment by Sweetygamer** [comment]
it's working, thanks !
