### ISSUE TITLE
Fox entity missing data for a white fox

### ISSUE THREAD

**Issue by Drexell** [CoolLord22/OtherDrops#110]
**Describe the bug**
There is no drop data for a white colored fox entity

**To Reproduce**
1. write a drop for a fox
2. try to add data for a white fox
3. notice it doesnt work
4. ask dev for help

**Expected behavior**
assuming data such as FOX@1 might drop a white fox ?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Java Version [e.g. 8 build 171]
 - Server Version [e.g. Spigot 1.12]
 - Plugin Version [e.g. 3.2.6 Legacy/1.13]

**Additional context**

**Comment by Achent007** [comment]
Hello,

Just found that was implemented !
you should use this : ENTITY_FOX@SNOW

and all should be good

But to be sure this os working, please use the last beta build avaiable on the discord !

**Comment by CoolLord22** [comment]
Reopening as I'm realizing the SNOW variant is the default so it *appears* to work but in actuality doesn't. New entities need to be added in manually.
