### ISSUE TITLE
Equiping hands not possible

### ISSUE THREAD

**Issue by Folas1337** [CoolLord22/OtherDrops#12]
# Bug report template 

**Description of the problem:** 
You can't equip an entities hands with the plugin.
Using "/odd zombie@eq:hands:diamond_sword" will only spawn a normal zombie with nothing in his hands. Replacing "hands" with "holding" has no effect either. I have also tried this with other mobs.

**How to replicate:** 
Use the mentioned command.

**Additional files:** 
No changes needed

**Checklist**:

- [x] I made sure I am using the latest version of OtherDrops
- [x] I made sure I am using a version of Minecraft supported by OtherDrops
- [x] I Made sure the bug/error is not caused by any other plugin
- [x] I included my dtherdrops-drops.yml and any relevant includes/changes I made.

**Provide additional information, such as error/debug/ logs. Use http://pastebin.com/ or similar for huge logs.**

**Comment by CoolLord22** [comment]
This might be because of a few changes I made in preparation for supporting both the main and offhand, try it with handsMain and handsOff which will correspond to their respective counterparts.

**Comment by CoolLord22** [comment]
My bad, I wasn't sure what the parameters were. Try out offHand and mainHand. They work for me!
