### ISSUE TITLE
Drops not working at all and a console error

### ISSUE THREAD

**Issue by GeMiniXCape** [CoolLord22/OtherDrops#14]
**Describe the bug**
When I try loading the plugin, I get this error. None of my drops work. I don't think it is the number ids. I went back to older versions of the plugin before # ids and it still doesn't work.

**To Reproduce**
1. https://pastebin.com/qwTdzuQs

**Comment by CoolLord22** [comment]
You’re right it’s not IDs it’s the loading of the known enum values. I thought I disabled that feature but I guess I forgot 😅. That feature just generates a file which contains all of the possible entries (like biomes, horse species, etc.) but doesn’t really serve a purpose. Try adding 

```
export_enum_lists: false
```

To your otherdrops-config.yml

**Comment by GeMiniXCape** [comment]
I no longer the error, but the drops aren't working. 
COAL_ORE:
        - drop: IRON_INGOT~&8Ashium/100%
          tool: DIAMOND_PICKAXE
This won't work in any version anymore.

**Comment by CoolLord22** [comment]
Can you please provide a list of plugins you are using on the server along with the exact server version (output of /version). Lastly, could you try running it on a clean server with no other plugins installed? It runs fine for me

**Comment by GeMiniXCape** [comment]
![screenshot_2353](https://user-images.githubusercontent.com/20043396/41942848-23127564-796f-11e8-9e4a-3fdcab408442.png)
![screenshot_2354](https://user-images.githubusercontent.com/20043396/41942850-25d77efc-796f-11e8-9b5a-b06a198051d2.png)

**Comment by CoolLord22** [comment]
Sorry, I was asleep when you responded (time zone differences have me going crazy 😂). But have you tried the rest of what I suggested? Like fixing the drop? Also, can you show the entire file?

**Comment by GeMiniXCape** [comment]
I fixed the drops! It was the spacing and the @~. However, I found a new problem. This one is with stained glass and stained glass panes. 

    GOLD_ORE:
        - drop: StainedGlass@Yellow@~&eThunder Stone/100%
          tool: ANY_PICKAXE

I followed what I did for the others, but StainedGlass and StainedGlassPanes won't work. (Btw ik what u mean :stuck_out_tongue_closed_eyes:)

**Comment by CoolLord22** [comment]
That would be because stainedglass isn’t the correct material, I believe it’s STAINED_GLASS. If you use the numerical ID, the plugin will produce a file containing the proper material name you need to change it to. And also, I believe the data is not specified correctly there. I think you need an ! between the @ and ~ but I’m not entirely sure.

**Comment by DragonisOmega** [comment]
STAINED_GLASS@Yellow  (yellow glass block 
STAINED_GLASS_PANE@Yellow  (yellow glass pane

**Comment by CoolLord22** [comment]
Assuming issue is fixed due to no response from creator. If you are still experiencing the issue, feel free to respond below and re-open it!
