### ISSUE TITLE
The OtherDrops plugin displaces the remuneration from the Jobs Plugin

### ISSUE THREAD

**Issue by Gniewny1** [CoolLord22/OtherDrops#16]
Drop Blocks entered in the otherdrops-drops.yml file displaces block shredding actions from the jobConfig.yml file and this operation, the pay system from Jobs stops working properly. Example: If a wood block drop exists in the otherdrops-drops.yml file, when being a lumberjack destroying such a block, I do not get money, points and exp. The same situation is in other blocks, eg block of dirt, when I work as a digger, I do not get compensation for destroying this block.

1.The worst thing is that Error on the console is not displayed.
2.The error can only be seen when you are working.

I didnt expect the contents of these two plugins to be mixed up and one will displace the other.

Screenshots:

Jobs plugin without the OtherDrops plugin
![image](https://user-images.githubusercontent.com/40638237/41987924-f49b74ac-7a3a-11e8-8237-78597046cd53.png)
As you can see the salary gets right away.

Plugin Jobs with the OtherDrops plugin
![image](https://user-images.githubusercontent.com/40638237/41987958-086822e6-7a3b-11e8-9b1c-ed5d6f9db5b7.png)
You see, nothing happens, I dont get a salary.

 - Windows 7
 - Java Version 8 build 171
 - engine: Spigot 1.12.2
 - Plugin OtherDrops Version 3.2.6
 - The file otherdrops-drops.yml: 
   https://megawrzuta.pl/download/1753745f9da1edc52774ddeb6dae27c9.html
 - Plugin Jobs Version 4.5.4
 - Type World: Void

From myself:
Personally, I regret that at the moment I cant use both this plugins at the same time :(.

**Comment by DragonisOmega** [comment]
I know the two plugins work together. I use both of them I would have looked at your drops.yml but my firewall hates whatever link that is.

**Comment by Gniewny1** [comment]
emm then How can I upload a file?

**Comment by DragonisOmega** [comment]
try pastebin

**Comment by DragonisOmega** [comment]
and there is a discord too

**Comment by Gniewny1** [comment]
https://cdn.discordapp.com/attachments/372052302439120908/461587218595708950/otherdrops-drops.yml

**Comment by DragonisOmega** [comment]
IRON_ORE:
        - trigger: BREAK
          tool: any_Pickaxe
          chance: .5
          Drop: Iron_Ore
          qauntity: 4-6
mine looks a bit like this I dont know if that's it?  are you getting any of the drops on yours?

**Comment by Gniewny1** [comment]
if that's what you mean then. Yes in my all drops working great.

**Comment by DragonisOmega** [comment]
you could have the drops be money or CoolLord22 just needs to make a jobs add on to go with this :)

**Comment by Gniewny1** [comment]
'LOG':
        - tool: ALL
          drop: LOG
          quantity: 1
          chance: 99
        - tool: ALL
          drop: OAK_WOOD
          quantity: 1
          chance: 4 
I think that "it" must be broken down into individual types of wood

**Comment by Gniewny1** [comment]
Even if I write separately all types of wood, I still do not know why I do not charge for digger work

**Comment by DragonisOmega** [comment]
wood is a feller job digger is for grass sand things with spade

**Comment by Gniewny1** [comment]
"wood is a feller job digger is for grass sand things with spade"  -_- I know it perfectly.

**Comment by Gniewny1** [comment]
I tested the digger work on all types of dirts and do not work.

**Comment by DragonisOmega** [comment]
ya if you add anything other then what it is suppose to be jobs wont pay you.

**Comment by DragonisOmega** [comment]
I dont know much about the permissions for both these plugins but maybe there is away that other drops will pay you if you have the permissions setup  like job digger has perm.digger and otherdrops pays you if you have perm.digger???  just a thought dont know if that would work.

**Comment by CoolLord22** [comment]
As a temporary fix try making LOG drop ```LOG@THIS```

**Comment by Gniewny1** [comment]
Okay, I'll do it, I'll open a clean file with otherdrops
and I will write the basic drops, then I will check if jobs will work properly.

**Comment by Gniewny1** [comment]
If i write some like this
    GRASS:
        - trigger: BREAK
          tool: ALL
          drop: STICK
          quantity: 1
          chance: 99
Then Natural drop (Grass) are replaced on a stick why??

**Comment by Gniewny1** [comment]
In the plugin would use the option: 
Do you want to keep the natural drop: True / False
And if you write True then you can add your drops

**Comment by Gniewny1** [comment]
And then there is a chance that jobs will work as it should

**Comment by DragonisOmega** [comment]
your saying that when you break grass it will drop stick.
you could try setting to true and see if it works.

**Comment by Gniewny1** [comment]
"your saying that when you break grass it will drop stick. <-- Yes
you could try setting to true and see if it works." <-- I dont be able write this option that it will works. Besides, I dont have access to it.

**Comment by CoolLord22** [comment]
Have you tried getting in touch with the creator of jobs to see why it doesn’t work? The issue isn’t with OtherDrops, it functions as intended. The main goal of the plugin is to change the vanilla drops. The problem arises because jobs doesn’t see that block being one for the job.

**Comment by CoolLord22** [comment]
> In the plugin should be option:
> (( Do you want to keep the natural drop: True / False ))
> And if you write True then you can add your drops
> And then there is a chance that jobs will work as it should
This already exists. What I suggest you do is add 
```
    ALL:
      - drop: DEFAULT```
to your drops file. This will ensure that the default drop is performed on EVERY block, mob, item, etc. If you add more drops they will drop too, so you could set a grass to drop gold nuggets, but the original grass will still drop.

**Comment by CoolLord22** [comment]
Confirmed to be working on 3.2.6 Beta with latest Jobs :)
