### ISSUE TITLE
Dark Oak and Acacia leaves does not drop items

### ISSUE THREAD

**Issue by ghost** [CoolLord22/OtherDrops#17]
**Describe the bug**

When i try to add drop to Dark oak or Acacia leaves it not works.

**To Reproduce**

1 - Add to config some drops :
    LEAVES@DARK_OAK:
        - tool: ALL
          toolexcept: SHEARS
          drop: INK_SACK@7~§fPussplum;§8apotheios:pussplum
          chance: 100
          quantity: 1

2 - The plugin recognize ID, but nothing drops when i break leaves

3 - https://hastebin.com/azipofewaf.md

NOTA :  

With LEAVES_2 olny without @DARK_OAK or 1/2 it works but on acacia and dark oak leaves, i want to have drops olny for Dark oak leaves.

**Comment by CoolLord22** [comment]
This also applies to logs for some reason, this issue is seriously strange... I found a fix for LEAVES but I can't seem to find the fix for LOGS...

**Comment by CoolLord22** [comment]
As said above, the issue's been fixed in 3.2.7. Please join the Discord server and check #beta_updates channel for the latest file.

**Comment by CoolLord22** [comment]
Closing as legacy build is no longer supported
