### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to OtherDrops v3.2.5

### ISSUE THREAD

**Issue by DragonisOmega** [CoolLord22/OtherDrops#18]
**Describe the bug**
Basically, you're trying to cast HuskData to LivingEntityData, and it doesn't like it. Error is at LivingEntityData.java:119

**To Reproduce**
1. Go to Survival.
2. Get Hit by a mob some number of times.
3. Scroll down to bottom of console.

**Expected behavior**
Honestly, no error expected.

**Screenshots**
https://pastebin.com/SrzpGvjm

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Java Version [8 build 171]
 - Server Version [Spigot 1.12.2]
 - Plugin Version [3.2.5]

**Additional context**
None.

**Comment by CoolLord22** [comment]
I can't seem to duplicate this bug, what mob are you saying the player should be hit by? Also, please attach any extra files you've changed! :)
