### ISSUE TITLE
Adding support for "zero damage value".

### ISSUE THREAD

**Issue by Zomblad** [CoolLord22/OtherDrops#21]
**Is your feature request related to a problem? Please describe:**
_Well, I was trying to replicate player's snowball/egg damage using OtherDrops plugin, because Spigot has some nasty bugs that prevents victims from getting this kind of damage at all. But the problem is that there is no support for zero damage in the plugin._

**Describe the solution you'd like:**
_I want to make "damage.victim" option being able to use "0" value. So it'll be possible to do a knockback do victims using snowballs/eggs, but not actually hurting them._

**Describe alternatives you've considered:**
_Sorry, but I'm very far away from such things as coding. Can't help you here._

**Additional context:**
_I hope that CoolLord22 won't be mind making this tiny but very handy upgrade to his plugin. Thanks._

**Comment by CoolLord22** [comment]
Let me know if that's what you wanted the feature request to work like. If not, feel free to reopen this issue. Thanks!

**Comment by CoolLord22** [comment]
Reopening as changes were made to source code regarding issue.

**Comment by CoolLord22** [comment]
Issue should have been fixed by most recent commits to legacy build. Please reopen it if you have any other problems with it!
