### ISSUE TITLE
Error on Server-Startup

### ISSUE THREAD

**Issue by L3v3lup** [CoolLord22/OtherDrops#23]
Hi, we already talked about the issue. Here again the Code.
(Probably caused by the latest CoreProtect Update)

> `[11:00:12 ERROR]: Error occurred while enabling OtherDrops v3.2.5 (Is it up to date?)
> java.lang.NoClassDefFoundError: net/coreprotect/CoreProtect
>         at com.gmail.zariust.otherdrops.Dependencies.loadCoreProtect(Dependencies.java:195) ~[?:?]
>         at com.gmail.zariust.otherdrops.Dependencies.init(Dependencies.java:114) ~[?:?]
>         at com.gmail.zariust.otherdrops.OtherDropsConfig.load(OtherDropsConfig.java:307) ~[?:?]
>         at com.gmail.zariust.otherdrops.OtherDrops.initConfig(OtherDrops.java:203) ~[?:?]
>         at com.gmail.zariust.otherdrops.OtherDrops.onEnable(OtherDrops.java:87) ~[?:?]
>         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-642f6d2-fbe3046]
>         at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-642f6d2-fbe3046]
>         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-642f6d2-fbe3046]
>         at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot.jar:git-Spigot-642f6d2-fbe3046]
>         at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot.jar:git-Spigot-642f6d2-fbe3046]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot.jar:git-Spigot-642f6d2-fbe3046]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot.jar:git-Spigot-642f6d2-fbe3046]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot.jar:git-Spigot-642f6d2-fbe3046]
>         at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-642f6d2-fbe3046]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-642f6d2-fbe3046]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
> Caused by: java.lang.ClassNotFoundException: net.coreprotect.CoreProtect
>         at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_171]
>         at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[spigot.jar:git-Spigot-642f6d2-fbe3046]
>         at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot.jar:git-Spigot-642f6d2-fbe3046]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
>         ... 16 more
>  `

**Comment by L3v3lup** [comment]
Well, i downloaded the new version of CoreProtect. After that, Otherdrops sent a couple errors on startup.
I took me some time to realise, that i have downloaded CoreProtect for 1.13 xD
Didnt even know, that the 1.13 was already out xD

**Comment by CoolLord22** [comment]
ahhhh understood xD
