### ISSUE TITLE
No knockback from getting damaged with a dispensed egg/snowball.

### ISSUE THREAD

**Issue by Zomblad** [CoolLord22/OtherDrops#25]
**Describe the bug:**
**_If egg or snowball gets dispensed at target with a dispenser, it won't deal any knockback to it. But in case of being thrown by someone (for example, another player), knockback works absolutely fine._**

**To Reproduce:**
Steps to reproduce the behavior.
**_Just use my configuration:_**

**_PLAYER:
        - trigger: HIT
           tool: PROJECTILE_SNOWBALL
           damage.victim: 0
           cooldown: damagecooldown1@0.0
           chance: 100.0
         - trigger: HIT
            tool: PROJECTILE_EGG
            damage.victim: 0
            cooldown: damagecooldown2@0.0
            chance: 100.0_**

**Expected behavior:**
**_I was expecting that dispensed egg/snowball would deal knockback to the targeted player._**

**Desktop (please complete the following information):**
- Java Version: 8 build 171.
- Server Version: Spigot 1.12.
- Plugin Version: 3.2.6 Legacy.

**Additional context:**
**_I hope that the bug would be fixed as soon as possible. Many thanks._**

**Comment by CoolLord22** [comment]
For Plugin Version, could you include whether it's tested on 1.13 or Legacy?

**Comment by CoolLord22** [comment]
For this, I can't seem to get a player to be able to hit themselves... Wasn't that possible at one point?

**Comment by CoolLord22** [comment]
Fixed the above bug about a player hitting themself, but the dispenser issue is being marked as invalid because  vanilla dispensers don't issue knockback regardless ^-^
