### ISSUE TITLE
GLASS_PANE does an oof

### ISSUE THREAD

**Issue by CrystalElixir** [CoolLord22/OtherDrops#26]
All types of `STAINED_GLASS_PANE` work (example - `RED_STAINED_GLASS_PANE`) except for the OG `GLASS_PANE` smh

**To Reproduce**
1. Make anything drop `GLASS_PANE`
2. Reload OD
3. Nothing - even if you put chance: 100

**Expected behavior**
A glass pane to drop :/

**Screenshots**
<img width="162" alt="screenshot at aug 07 12-54-05" src="https://user-images.githubusercontent.com/42077134/43798974-01671df0-9a41-11e8-803a-9dbc793a2d6e.png">
![2018-08-07_12 54 47](https://user-images.githubusercontent.com/42077134/43799023-23f6f444-9a41-11e8-8087-04b05e81cf43.png)
![2018-08-07_12 54 50](https://user-images.githubusercontent.com/42077134/43799386-3ca466b0-9a42-11e8-9e88-f7f8ecb25e74.png)
):<

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.13.3
 - Java Version: 8 build 171
 - Server Version: Spigot Development 1.13
 - Plugin Version 3.2.6 1.13

**Comment by CoolLord22** [comment]
Any relevant console messages? Try turning verbosity up to highest and seeing then (in config file)

**Comment by CrystalElixir** [comment]
```[13:36:31 INFO]: [OtherDrops_1.13:3.2.6] PerformDrop - potential drops found: [BREAK on GLASS drops NULL, BREAK on GLASS drops GLASS] tool: PLAYER@CrystalElixir with DIAMOND_PICKAXE@1/1
[13:36:31 INFO]: [OtherDrops_1.13:3.2.6] PerformDrop: scheduling NULL
[13:36:31 INFO]: [OtherDrops_1.13:3.2.6] Message action - messages = [» Damn, you suck at this.], message=» Damn, you suck at this., type=ATTACKER
[13:36:31 INFO]: [OtherDrops_1.13:3.2.6] PerformDrop: finished. defaultdrop=false dropcount=0 cancelled=false denied=false```

```[13:38:27 INFO]: [OtherDrops_1.13:3.2.6] PerformDrop - potential drops found: [BREAK on CREATURE_PIG drops NULL] tool: PLAYER@CrystalElixir with DIAMOND_SWORD@/1
[13:38:27 INFO]: [OtherDrops_1.13:3.2.6] PerformDrop: scheduling NULL
[13:38:27 INFO]: [OtherDrops_1.13:3.2.6] PerformDrop: finished. defaultdrop=false dropcount=0 cancelled=false denied=false```

**Comment by CoolLord22** [comment]
What about when you load the drops up? So /odr

**Comment by CoolLord22** [comment]
Send me the drops file you're using, I'm a little confused what you mean.
