### ISSUE TITLE
Bukkit/Spigot cannot pass event EntityDeathEvent.

### ISSUE THREAD

**Issue by pvpKingdoms** [CoolLord22/OtherDrops#27]
Description: Basically, killing entities (mobs and players from what I can gather) tries to register but cannot pass as the title says. Whole console was spammed with this error.
Console error - Could not pass event EntityDeathEvent to OtherDrops_1.13 v3.2.6

Reproduction:
Kill a mob; I only had cow listed in the drops.yml but I was getting errors for any mob killed.

Expected Behavior: 
Expected mobs from drops.yml to execute the command/drop the item I specified.

Desktop:
 OS: Windows 10 Pro
Java Version: 10.0.2
Spigot Version: 1.13
Plugin Version: 1.13

**Comment by CoolLord22** [comment]
Are you using build 3.2.5 or 3.2.6?

**Comment by CoolLord22** [comment]
The issue is only occurring when the player is executing a command. Need to investigate why it does so.

**Comment by CoolLord22** [comment]
StackTrace: https://pastebin.com/kD3ZRNDa
