### ISSUE TITLE
Adding fortune that can change drop

### ISSUE THREAD

**Issue by BlackAndWhitee** [CoolLord22/OtherDrops#29]
**Is your feature request related to a problem? Please describe.**
Currently on version 2.5 you cant set custom drops for tools with fortune enchant, for example : 
            tool: [DIAMOND_PICKAXE, -DIAMOND_PICKAXE!LOOT_BONUS_BLOCKS#3, -DIAMOND_PICKAXE!LOOT_BONUS_BLOCKS#2, -DIAMOND_PICKAXE!LOOT_BONUS_BLOCKS#1] 

dont work, pickaxes without enchant dont drop anything

**Describe the solution you'd like**
Adding option to specify the items with fortune enchant

**Comment by CoolLord22** [comment]
Could you follow the format for a feature request? I edited the original message posting the format you should use :)

**Comment by CoolLord22** [comment]
The enchantment for fortune is now known as `fortune` Check out the includes folder and the Enchantments.txt file. Closing issue for now, if you still experience this issue feel free to reopen.
