### ISSUE TITLE
Could not pass event VehicleDestroyEvent

### ISSUE THREAD

**Issue by ArZorMC** [CoolLord22/OtherDrops#34]
My guess is otherdrops is looking for methods that no longer exist in worldguard causing it to throw console errors.

Should be able to reproduce by having worldguard and otherdrops installed and try to break a boat.

Screenshot of the error:
https://gyazo.com/3318456b558b381ff68f3ce962a9ff92

 - Java Version 8 
 - Server Version 1.13.1.jar:git-Paper-248
 - Plugin Version OtherDrops_1.13 v3.2.6

**Comment by CoolLord22** [comment]
Please make sure you check closed issues, this has been reported 3 times and is solved in a beta branch. It’ll be released shortly
