### ISSUE TITLE
Language Feature 

### ISSUE THREAD

**Issue by Misio12320** [CoolLord22/OtherDrops#36]
Hello can you please make a per World drop or Just like a hm Otherdrops working on 1world and on the 2th doesnt work some like this? And if possible make a language support /od help and custom language like Deutsche etc maked by own self in languages.yml

**Comment by CoolLord22** [comment]
For world drops it already exists, at the top of the drops file you can set default values, where it says `defaults: `
Just add this into there:
`defaults:
    worlds: [world1, world2, world3, etc]`

**Comment by Misio12320** [comment]
Where can I find this? Well I used this plugin 1 time hm..

**Comment by Misio12320** [comment]
And can I get 1 example of OtherDrops drop,message and drop? without # and spaces

**Comment by CoolLord22** [comment]
I'm not sure what you mean, could you please explain?

**Comment by Misio12320** [comment]
I want completed 1  drop Diamond 90% and world selected all done next like in this Otherdrops.yml there is a example and I want from you it because idk how to write it... With world drop only 1
