### ISSUE TITLE
EndermanData material conversion

### ISSUE THREAD

**Issue by CoolLord22** [CoolLord22/OtherDrops#38]
**Describe the bug**
Issue with EndermanData trying to convert new data of Modern Material

**To Reproduce**
n/a

**Expected behavior**
No error output in console when using enderman drops

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Java Version [8 build 191]
 - Server Version [Spigot 1.13]
 - Plugin Version [3.2.7 1.13]

**Additional context**
n/a

**Comment by CoolLord22** [comment]
Updating issue with pastebin error: https://pastebin.com/nSZTiyQj

**Comment by CoolLord22** [comment]
Hey, it’s been fixed on 3.2.7 so if you’d like the fixed version you can grab it from our Discord server

**Comment by khamseen** [comment]
Hey, cool thanks man. I joined the Discord and downloaded version 3.2.7 so I'll give it a whirl. 👍
