### ISSUE TITLE
cosume tool lore check not work

### ISSUE THREAD

**Issue by WindUnwaken** [CoolLord22/OtherDrops#40]
**Describe the bug**

defaults:
    worlds: ALL
    trigger: RIGHT_CLICK

otherdrops:
    OAK_LEAVES:
      - tool: BEETROOT_SEEDS@~§3TEST;§aLORE
        consumetool: 1
        replacementblock: FLOWER_POT

We can only just have BEETROOT_SEED with NAME:§3TEST can trigger this.
Plugin seems not check lore for specified item

 - Plugin Version 3.2.7 build ; spigot:1.13.2

**Comment by CoolLord22** [comment]
Confirmed to be an issue on both legacy and 1.13 builds. Need to do a lot of digging to figure out why this feature broke.

**Comment by CoolLord22** [comment]
As marked above, this issue has been fixed. It will be closed once the code changes are pulled into the master branch. Thank you for reporting it! If you would like to test this version, please join the plugin's Discord server and enroll as a Beta tester. It can be found in #beta-updates.
