### ISSUE TITLE
Bug with Unbreakable Item

### ISSUE THREAD

**Issue by dewobedil** [CoolLord22/OtherDrops#41]
**Steps to reproduce the behavior:**
When an item using Unbreakable and it has custom texture using resourcepack then when i make drop config example:

    GRASS:
        - tool: WOODEN_SWORD@~Crude Knife
          drop: TALL_GRASS

The item will stay unbreakable but the texture changed in misterious way It should never changed tool durability or texture in anyway

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Java Version 8 build 191
 - Server Version Spigot 1.13.2
 - Plugin Version 3.2.6 1.13

**Comment by CoolLord22** [comment]
Try adding 
`
damage.tool: 0
`
which will make sure the tool doesn’t take damage. The plugin damages regardless of the data on the tool.

**Comment by dewobedil** [comment]
ok i put the damage.tool: 0
but its still happening

and one more thing when i add chance on the drop
when tool break blocks it will not change the texture, but when the tool meet the chance drop it will change the texture.

sorry for my english xD

**Comment by dewobedil** [comment]
thank you !! it worked

**Comment by dewobedil** [comment]
i used damagetool: not damage.tool:
