### ISSUE TITLE
Chicken food bug

### ISSUE THREAD

**Issue by dewobedil** [CoolLord22/OtherDrops#42]
**Describe the bug**
plugin detect RAW CHICKEN food as entities so i cant make CHICKEN as a tool, so when i used trigger CONSUME_ITEM it doesnt work, also RAW COD, minecraft:cod

**Desktop:**
 - OS: Windows 10
 - Java Version 8 build 191
 - Server Version Spigot 1.13
 - Plugin Version 3.2.6 1.13

**Additional context**
Maybe you can make support for the LEGACY_ version for the material https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
or maybe create an alias for them.

**Comment by CoolLord22** [comment]
This is also an issue on Cod as well. I'm thinking the best way to fix this issue would be to require CREATURE_ on all mobs again, opinions?
