### ISSUE TITLE
EntityDeath related event causing TPS drop on server.

### ISSUE THREAD

**Issue by 1jonny1** [CoolLord22/OtherDrops#45]
On our server OtherDrops seems to be causing lag.
From timings is seems to be coming from a entity dieing.

If we unload otherdrops the server will run at 20Tps just fine.
If we load otherdrops the tps will drop to about 12-11tps within about 30s
If we keep the plugin loaded AND disable mob spawning on the server it will stay at 20tps when we enable the mob spawning the tps will drop

Timings report from the server.
https://timings.aikar.co/?id=5a4f692da7604d3389e252b52eb021ba#plugins

Source: https://gyazo.com/5616c68c1774bc208c9a32e0a132d29c

As you can see the call count is rather high as there is always a LOT of mobs dieing but that should not make a difference.

Here is the code from the Minion plugin that kills the mobs
final Damageable damageable = (Damageable) entity;
damageable.damage(1000);

Server info:
https://gyazo.com/47569b487b763a5331be6f3f2efda89b

OtherDrops Version (From plugin.yml):
https://gyazo.com/8f07c07f760130701c44d94452afdd6a

**Comment by CoolLord22** [comment]
Could you please update this with the format for bug reports? Including your server version and etc?

**Comment by 1jonny1** [comment]
**Describe the bug**
Tps Drops

**To Reproduce**
Steps to reproduce the behavior:
NA

**Expected behavior**
Not to drop TPS

**Screenshots**
See 1st post.

**Desktop (please complete the following information):**
 - OS:  linux
 - Java Version: 
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-0ubuntu0.16.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

 - Server Version: Paper 1.12
 - Plugin Version: 3.2.6

**Additional context**
See 1st post.

**Comment by CoolLord22** [comment]
Thank you! I’ll work on this once I’m home.

**Comment by CoolLord22** [comment]
Could you attempt to use OtherDrops without the Minions plugin and see if that has an impact on tps? If this isn't a valid option, can you contact me on Discord? I'd like to work this out over direct message as it's a faster method of communication.

**Comment by CoolLord22** [comment]
Update on this issue, it will only cause lag with thousands upon thousands of drops being run every tick.
