### ISSUE TITLE
position of the replacement

### ISSUE THREAD

**Issue by hacecah** [CoolLord22/OtherDrops#52]
i think it will be interesting to add a relative/absolue position to the block that replaces the block we break.
it will open a new dimension.
for exemples :
- we will do a monster spawning near the position but not at the position (in the sky a phantom for exemple)...
- we can do more than one explosion that can create a dangerous zone around the miner...
- we can spawn the enderdragon where the server-dev wants if we use on the good block an item like "The-Enderdragon-Pickaxe"
- ...

Thank you for your job ! This plugin is epic !

**Comment by CoolLord22** [comment]
As this is already a feature in the plugin I'm marking this as closed. Thank you for using GitHub!
