### ISSUE TITLE
Bug Plz Help

### ISSUE THREAD

**Issue by UMOMaster** [CoolLord22/OtherDrops#54]
On Console: https://pastebin.com/mWT3s7jt
Drop: https://pastebin.com/KZ47Y2t8
Config: https://pastebin.com/yzzNtwz0

**Comment by CoolLord22** [comment]
I said this in my PM too, you are using a 1.12 / 1.13 plugin on a 1.8 server. Please update your server to receive support. If you need the plugin for 1.8, you’ll have to use the version on Bukkit.
