### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by UMOMaster** [CoolLord22/OtherDrops#57]
Can you Help My OtherDrops Plugins is BUG. Version server 1.8-1.13 (Viaversion)
Console:  https://pastebin.com/mWT3s7jt
Drop:  https://pastebin.com/KZ47Y2t8
Config:  https://pastebin.com/yzzNtwz0

**Comment by CoolLord22** [comment]
Once again, you’re still using a 1.8 server. If you look at the log, your jar is org.bukkit.craftbukkit.v1_8_R3. Until you update to v1_12_R1 I cannot help. To use 1.8.3, you can download https://dev.bukkit.org/projects/otherdrops
