### ISSUE TITLE
Permissions error when using permissions

### ISSUE THREAD

**Issue by dean142** [CoolLord22/OtherDrops#6]
# Bug report template 

**Description of the problem:** 
Permissions error when using permissions

**How to replicate:** 

Use this in otherdrops-drops.yml https://imgur.com/a/0THpk

**Additional files:** 

Console error https://pastebin.com/0JLt32tY

**Checklist**:

- [x] I made sure I am using the latest version of OtherDrops
- [x] I made sure I am using a version of Minecraft supported by OtherDrops
- [x] I Made sure the bug/error is not caused by any other plugin
- [x] I included my dtherdrops-drops.yml and any relevant includes/changes I made.

**Provide additional information, such as error/debug/ logs. Use http://pastebin.com/ or similar for huge logs.**

**Comment by CoolLord22** [comment]
Thanks for the report! I’m aware of the issue and am currently looking into why it’s happening. I haven’t been able to get the old plugin to allow me to set permissions either (on 1.9 at least) so I’m assuming there’s a few changes in the API. No worries, I’ll look into the issue and figure out why it’s happening!

**Comment by CoolLord22** [comment]
Hey @dean142! I believe this issue has been addressed and fixed in the dev-branch. I'm basically adding a lot of fixes there before I release the plugin publicly. If you don't mind, do you have any other means of communication so I can give you beta version?

**Comment by dean142** [comment]
Discord is: dean142#4086

**Comment by CoolLord22** [comment]
@dean142 https://www.spigotmc.org/resources/otherdrops-updated.51793/updates contains the latest release, as does https://github.com/CoolLord22/OtherDrops/releases Do look at the update notes and Wiki for information on what has changed. It is a Beta release so it may not be fully stable. I have tested it quite heavily and everything seems operational.

**Comment by CoolLord22** [comment]
Fixed by 
https://github.com/CoolLord22/OtherDrops/commit/ed74c56fe0583c9a09968fdaa9662f868f2a1564
