### ISSUE TITLE
Fishing Configuration

### ISSUE THREAD

**Issue by Bobbiimarcil** [CoolLord22/OtherDrops#61]
Hello I would like to customize the fishing on my server. I wonder how to configure this. the documentation for that seems rare. For example, if I want my players to catch 80% 1 trout and 20% 1 emerald. But never vanilla rewards. How should I write it?

Thank you in advance! :)

**Comment by CoolLord22** [comment]
Sorry about not having all of the documentation released yet, still trying to get everything on the wiki :(
As to your answer, the fishing trigger is called on the player. So you'd do:

`PLAYER:
      - trigger: FISH_CAUGHT
        drop: ITEM (TROUT)
        chance: CHANCE (80)
        flags: UNIQUE (This is if you want just 1 drop rather than multiple items dropping from a fish getting caught, meaning the Emerald won't drop at the same time as the Trout)
      - trigger: FISH_CAUGHT
        drop: ITEM (EMERALD)
        chance: CHANCE (20)
        flags: UNIQUE (This is if you want just 1 drop rather than multiple items dropping from a fish getting caught, meaning the Emerald won't drop at the same time as the Trout)`

**Comment by k9lego** [comment]
Any way to adjust the drop chance based on Luck of the Sea? Thanks! :)

**Comment by CoolLord22** [comment]
You can follow the basic tool enchantment process and specify the tool as a fishing rod with the enchant  :)
