### ISSUE TITLE
Remove large red error block and replace it with "Could not connect" or something

### ISSUE THREAD

**Issue by DarkMonolith** [CoolLord22/OtherDrops#62]
**Is your feature request related to a problem? Please describe.**
Its annoying when booting up the server to see a spam of Connection error blocks that take up the whole screen multiple times

**Describe the solution you'd like**
Make it not do that, but maybe just say "Could not connect" once

**Describe alternatives you've considered**
idk, man. leave it as is? its pretty annoying

**Additional context**
https://cdn.discordapp.com/attachments/418438070812147723/565596179971309579/unknown.png

**Comment by CoolLord22** [comment]
This is actually an issue with Paper and how long your connection to Spiget's plugin query takes. The commit that changes WatchDog is here, you can modify settings.watchdog.early-warning-every and
settings.watchdog.early-warning-delay as OD took more than the configured 10 seconds to reach its update servers. https://github.com/PaperMC/Paper/commit/dc428860cf1ef8df4df5b53b97ea61f551f50b11
