### ISSUE TITLE
Default Drops and Discord

### ISSUE THREAD

**Issue by Aeyori** [CoolLord22/OtherDrops#63]
**Description of the problem:** 	
Hi! I was curious to know whether this plugin would be able to disable default drops of a mob in certain worlds as well as give them custom drops of custom items from another plugin MmoItems to be specific). I have checked the wiki but I don't see any config section about removing default drops for a mob.

I also have thumbs-ed up the discord-welcome channel but the server is still not showing up for me.
**How to replicate:** 	
	
	N/A
**Additional files:** 	
	
N/A
**Version Information (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Java Version [e.g. 8 build 171]
 - Server Version [e.g. Spigot 1.12]
 - Plugin Version [e.g. 3.2.6 Legacy/1.13]
 N/A
**Checklist**:	
	
- [] I made sure I am using the latest version of OtherDrops	
- [] I made sure I am using a version of Minecraft supported by OtherDrops	
- [] I Made sure the bug/error is not caused by any other plugin	
- [] I included my otherdrops-drops.yml and any relevant includes/changes I made.	
	N/A
**Provide additional information, such as error/debug/ logs. Use http://pastebin.com/ or similar for huge logs.**

**Comment by CoolLord22** [comment]
For the discord issue, you’ll have to double check if the Reaction Role bot is offline, and if so just contact a staff member to manually add the role. 

In regards to mmoitems, adding support for every custom item plugin would be difficult however OD does have a command action which can be used to give the players the item (if the plugin has a command feature to give players an item, or drop it). The alternative would be to use the give command to give the player the item with all of the correct data needed. 

I am, however, in the process of adding support for MythicMobs which you might be able to spawn a custom mob to drop an item from mmoitems if absolutely necessary?
