### ISSUE TITLE
Block Data (DOUBLE_PLANTS)

### ISSUE THREAD

**Issue by Naghell** [CoolLord22/OtherDrops#72]
**Description of the problem:** 	I want that when breaking a specific flower or double plant, it produces an effect. But when placing the data-value, the drop stops working in any form.

**How to replicate:** 	Use this config or relative and try xD

  DOUBLE_PLANT@1:
  - drop: AIR
    trigger: BLOCK_BREAK
    potioneffect: poison@140@1
    sound: ENTITY_SPLASH_POTION_BREAK
    message: "&f<Tú>: &6Creo que he tocado una hierba venenosa."
    chance: 100%
    flags: UNIQUE
	
**Additional files:** 	
Nothing to add.

**Version Information (please complete the following information):**
 - Server Version: Spigot 1.12
 - Plugin Version: 3.2.7BETA
 
**Checklist**:	
- [X] I made sure I am using the latest version of OtherDrops	
- [X] I made sure I am using a version of Minecraft supported by OtherDrops	
- [X] I Made sure the bug/error is not caused by any other plugin	
- [X] I included my otherdrops-drops.yml and any relevant includes/changes I made.	
	
**Provide additional information, such as error/debug/ logs. Use http://pastebin.com/ or similar for huge logs.**
The log files say absolutely nothing. It's strange.

**Comment by CoolLord22** [comment]
No longer supporting legacy branch; if issue exists on 1.13Plus please reopen.
