### ISSUE TITLE
Ocelot/Cat data bug

### ISSUE THREAD

**Issue by Drexell** [CoolLord22/OtherDrops#76]
**Describe the bug**
Basicly some sort of warning spams console related to ocelot drops due to data or tag issues from what I understand.

**To Reproduce**
I believe its just anything related to ocelots and or their drops.  (maybe check wolves too? haven't seen an error for it though)

**Expected behavior**

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Java Version: 1.8.0
 - Server Version: Paper-117
 - Plugin Version: Newest beta 3.2.7

**Additional context**

**Comment by CoolLord22** [comment]
Believe these issues have been addressed by latest releases. If you run into errors, please reopen.
