### ISSUE TITLE
xp multiplier for spawner mobs, doesn't affect xp drop from world mobs

### ISSUE THREAD

**Issue by weinerman00** [CoolLord22/OtherDrops#77]
i would really like to see an xp multiplier setting on mobs spawned from spawners, that doesn't affect the xp drop you get from monsters that spawn at night/at caves.  

i have an example of it from mcmmo and i'd love to use this plugin to modify my spawner farms while nerfing the xp drop
![image](https://user-images.githubusercontent.com/52538911/61097623-9d36c880-a421-11e9-818b-8024892949f1.png)

**Comment by CoolLord22** [comment]
You can specify custom xp levels from mobs that are spawned via a mob spawner! While it isn't a multiplier, you can specify them to drop more experience that way. I don't think OD implements a multiplier per se, but if it does, you can add `spawnedby: MOB_SPAWNER` to the drop and it'll only apply that drop to mob spawner monsters.
