### ISSUE TITLE
Need help asap

### ISSUE THREAD

**Issue by mlodydemon** [CoolLord22/OtherDrops#8]
Can i add to drop items from other plugins?
In that case i want to add case's and key's from ItemCases to drop from stone.
thanks for help if i get response

**Comment by CoolLord22** [comment]
Hi there! Thank you for using this plugin! You can specify a command to be run each time a block is broken (if you'd like to use the crate plugin's command), or you can modify the name, lore, and enchants to match those from the crate plugin (e.g. TRIPWIRE_HOOK@!~My Key;Lore line;Lore line;etc. (<<< this may be formatted incorrectly so if you need any more help please let me know!)

P.S. Sorry for the late response, I usually check GitHub later in the day and am more active on Discord. Feel free to join our server here: https://discord.gg/eHBxk5q

**Comment by CoolLord22** [comment]
Also, check out https://www.spigotmc.org/threads/otherdrops-updated.295533/page-2#post-2913953 if you need help finding out how to run commands for drops.

**Comment by mlodydemon** [comment]
Thanks for the response, the command is /case givecase {player} Skrzynka 1 from ItemCases plugin

**Comment by mlodydemon** [comment]
Okay i figured it out myself thanks
