### ISSUE TITLE
coreprotect error

### ISSUE THREAD

**Issue by Devillion** [CoolLord22/OtherDrops#80]
**Describe the bug**
Getting this error on startup https://pastebin.com/xTtmt3cj

**To Reproduce**
Start up the server running 1.13.2

**Expected behavior**
no errors

**Desktop (please complete the following information):**
 - OS: are you talking about my servers os? if so it's ubuntu 18.04
 - Java Version 8
 - Server Version paper 1.13.2
 - Plugin Version 1.13.2 (not legacy version)

**Comment by CoolLord22** [comment]
Update regarding this, it is in fact, a CoreProtect issue (unrelated to OtherDrops)

`[22:39:43 INFO]: [CoreProtect] Enabling CoreProtect v2.16.3
[22:39:43 INFO]: [CoreProtect] CoreProtect 2.17.0 or higher is required.
[22:39:43 INFO]: [CoreProtect] CoreProtect was unable to start.
[22:39:43 INFO]: [CoreProtect] Disabling CoreProtect v2.16.3`

CoreProtect 2.16.3 seems to fail continuously on Spigot build 1.13 and thus OtherDrops is unable to find it. Removing Cannot Replicate, adding Invalid.

**Comment by CoolLord22** [comment]
Follow up comment, CoreProtect issue seems to be found here: https://www.spigotmc.org/threads/coreprotect.73929/page-65#post-3421973
