### ISSUE TITLE
Consume Item

### ISSUE THREAD

**Issue by WizardPulse** [CoolLord22/OtherDrops#81]
**Is your feature request related to a problem? Please describe.**
It's a problem for my heart :(

**Describe the solution you'd like**
Would love to make it so you can consume an item upon use.

Example: I use a fishing rod to catch a diamond, and when it's caught a dirt block will be consumed. Item is only consumed if the fish/item is caught.

Can be applied to many things, but I'd love it for fishing so I can make fishing bait.

**Describe alternatives you've considered**
I've considered crying and removing my reaction to the #terms-and-conditions channel in Discord

**Additional context**
None

**Comment by CoolLord22** [comment]
Achievable by using `consumetool: 1` on the drop group.
