### ISSUE TITLE
Can't figure out how to run a command when killing a mob

### ISSUE THREAD

**Issue by Noodle3884** [CoolLord22/OtherDrops#82]
I've been attempting to allow hostile mobs to possible give a crate key when killed (a percentage chance); however, I can't figure out what info I actually need to put in the otherdrops-drops.yml file. I also wanted to set up fishing command rewards with that but I didn't see info on your github pages about it and I am too stupid with code to do it myself so if you could help by giving a layout or example on that it would be amazing.

**How to replicate:** 	
Not applicable
	
**Additional files:** 	
https://github.com/Noodle3884/Otherdrops-drops-yml

**Version Information (please complete the following information):**
 - OS: Windows 10
 - Java Version  8 build 211
 - Server Version Spigot 1.14.4
 - Plugin Version 1.13
 
**Checklist**:	
	
- [X] I made sure I am using the latest version of OtherDrops	
- [X] I made sure I am using a version of Minecraft supported by OtherDrops	
- [X] I Made sure the bug/error is not caused by any other plugin	
- [X] I included my otherdrops-drops.yml and any relevant includes/changes I made.	
	
**Provide additional information, such as error/debug/ logs. Use http://pastebin.com/ or similar for huge logs.**
I am terrible with this stuff so sorry if this is a very obvious issue with what I put in (I know it is something I am doing, this is also my first time using github sorry if I should have filled this out differently.

**Comment by CoolLord22** [comment]
Going off of the past edited message, fishing is found in #faq on our Discord, but I’m assuming you’ve figured it out as you closed the issue ;). If you need anything else, feel free to ask in #otherdrops-support channels!
