### ISSUE TITLE
Feature request to be able to prevent dropping of items for players in certain situations

### ISSUE THREAD

**Issue by axemwa** [CoolLord22/OtherDrops#83]
**Describe the solution you'd like**
Feature request to be able to prevent dropping of items for players on first attempt of the drop "Q" button for items that are on a list in the config and to add a bypass permission so that if a player has the bypass permission they can drop the item straight away ignoring the plugin.

Also to add worldguard compatibility/region support so that if players try to drop any of the items listed in the conifg menioned above when in a blacklisted region to cancel being able to drop that item entirely instead of just the first drop attempt, which should help prevent dupes if worldguards antidrop feature is enabled which in turn should also allow you to specifically configure which items can or can't be dropped in the worldguard region, instead of just preventing all items from being dropped which is what would guard does, if that makes sense

Main reasoning for entirely disabling antidropping of specific items in specific worldguard regions is so that dupes don't occur like in other antidrop plugins if worldguards anti drop feature is enabled like this person has mentioned
![image](https://user-images.githubusercontent.com/37608633/62841814-69361800-bceb-11e9-9758-4230b48f6674.png)

**Comment by CoolLord22** [comment]
If we inspect how OtherDrops works, we can make it similar to the fishing event. Where tool will be the item that is being dropped by the player, and the trigger will be item drop. The event can, in theory, be cancelled.

**Comment by CoolLord22** [comment]
Also thought I'd drop this tidbit, OtherDrops does have region support built in, so it would first depend off of that and then proceed to cancel ;) experiment around with how OtherDrops works with the basic features :)

**Comment by DaddySpin** [comment]
If you add this can you make it so if you press Q twice then it will allow you to drop the item as like an option?

**Comment by CoolLord22** [comment]
Can you folks join the Discord server for OtherDrops so we can discuss some more features in depth there? @DaddySpin @axemwa

**Comment by DelKatey** [comment]
> 
> 
> If you add this can you make it so if you press Q twice then it will allow you to drop the item as like an option?

And optionally make it so that users can use a command to toggle this behaviour for themselves, too

**Comment by CoolLord22** [comment]
> > If you add this can you make it so if you press Q twice then it will allow you to drop the item as like an option?
> 
> And optionally make it so that users can use a command to toggle this behaviour for themselves, too

Unfortunately, this feature likely wont be added as the only commands OtherDrops needs are ones to modify drops. Adding a toggle is nothing related to OtherDrops. However, since OtherDrops does support permissions for drops, you can add a custom command to give/remove the permission using another plugin.

**Comment by axemwa** [comment]
Request has been implemented, thankyou oh Lord heh ;)

**Comment by CoolLord22** [comment]
Leaving this opened until the pull request containing the feature is added into the master branch :)
