### ISSUE TITLE
Drops with enchanted pickaxes

### ISSUE THREAD

**Issue by antolo-arch** [CoolLord22/OtherDrops#87]
I'm trying to customise some item drops from cobblestone. So for exapmple If i had an enchanted pickaxe, with only one enchant (Fortune) I was able to modify the drop as I wanted. The problem occured when i was trying to modify the drop for the pickaxe with more than one enchant, for example efficiency 4 unbreaking 3 fortune 3. Is there an option to define a drop for a pickaxe with fortune no matter what other enchants are?

**Comment by CoolLord22** [comment]
@antolo-arch I believe your issue can be solved by the enchantment restriction in the config; 

``` 
# Restrict matching: when true, it will require enchantments to be exactly how they are configured in the drops file
# (for example, A pickaxe defined with Fortune 3 will only let a Fortune 3 pickaxe perform the drop. To allow a
# fortune 3, unbreaking 5, and efficiency 5 pickaxe to perform the drop, set this value to false.

enchantments_restrict_matching: true
```
If that doesnt solve your problem, can you provide us the following data? 
**Additional files:** 	
_If you have made modifications to your otherdrops-config.yml or otherdrops-drops.yml file, or the includes files, please attach them here_

**Version Information (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Java Version [e.g. 8 build 171]
 - Server Version [e.g. Spigot 1.12]
 - Plugin Version [e.g. 3.2.6 Legacy/1.13]
	
**Provide additional information, such as error/debug/ logs. Use http://pastebin.com/ or similar for huge logs.**

**Comment by antolo-arch** [comment]
Thanks, problem solved :)

**Comment by CoolLord22** [comment]
Marking thread as solved
