### ISSUE TITLE
Lapis Lazuli problem

### ISSUE THREAD

**Issue by xCin3kk** [CoolLord22/OtherDrops#89]
I have a problem with Lapis Lazuli, Lapis it's unstackable.

I have problem with Lapis Lazuli drop. When i digs Stone, Lapis drops but it's unstackable with Lapis from Ore, because Lapis from drop has a 1 NBT Tag.

This is Lapis Lazuli config
        - drop: LAPIS_LAZULI
          tool: [STONE_PICKAXE, IRON_PICKAXE, DIAMOND_PICKAXE]
          chance: 2
          quantity: 4-8
          delay: 1
          loc-offset: 0/-1/0

**Desktop (please complete the following information):**
 - OS: Windows
 - Java Version Java 8 build 231
 - Server Version Spigot 1.13.2
 - Plugin Version 3.2.6 Legacy 1.13.2

**Comment by CoolLord22** [comment]
Cannot replicate on 3.2.7, if you're still experiencing issues please reopen!
