### ISSUE TITLE
Iron Ore 

### ISSUE THREAD

**Issue by MatteonX** [CoolLord22/OtherDrops#95]
Hello, I have a question about OtherDrops, I want to drop from iron ore (NOT FROM STONE). 
It is supposed to look so that ore is kicked normally, but for example there is less chance of their falling out. 
I did something like this: 

include-files:
aliases:
defaults:
otherdrops:
    IRON_ORE:
        - drop: STONE
          quantity: 1
          chance: 50
          tool: [STONE_PICKAXE, IRON_PICKAXE, DIAMOND_PICKAXE, GOLDEN_PICKAXE]
          message: 'stone'
        - drop: DIAMOND
          quantity: 1
          chance: 50
          tool: [STONE_PICKAXE, IRON_PICKAXE, DIAMOND_PICKAXE, GOLDEN_PICKAXE]
          message: 'diament'
          
But when it starts digging iron, it still falls, although I did not add it to the drop.
The added drop works, but the iron falls out, although it should not.
Can it be written differently?
I can share the screen on discord if needed and see what it looks like.

**Comment by CoolLord22** [comment]
Correct me if this is wrong, but are you trying to just make the breakage drop nothing? If so, you’ll need to add a drop: NOTHING so that the default drop is always overridden. Let me know if this helps, or if you’re trying to accomplish something else.

**Comment by MatteonX** [comment]
I mean the iron drop chance was 10% and the rest 90% is stone, But let it be in IRON_ORE

**Comment by CoolLord22** [comment]
Can we take this over to discord in maybe half an hour? I just got out of a lecture so I’ll be able to help out soon. Feel free to leave a message on the OtherDrops support channel with your question so I know who to tag when trying to set up a meeting!

**Comment by CoolLord22** [comment]
Resolving via Discord support.
