### ISSUE TITLE
Otherdrops 1.15

### ISSUE THREAD

**Issue by xHaCek** [CoolLord22/OtherDrops#96]
Hello
I want to thank you for otherdrops update, it’s great! I wanted to update it to 1.15 but i cant ☹.  Can you please update this plugin to 1.15? It would be great!

**Comment by ClarkWolfang** [comment]
Actually, the only version that works with 1.15, it's OtherDrops 3.2.7beta
You can get it in the beta-updates section of the discord channel.

**Comment by CoolLord22** [comment]
^^ Sorry I thought I responded to this but apparently forgot to actually comment what I had typed lol.
