### ISSUE TITLE
Mistake in FAQ, on the plugin wiki page

### ISSUE THREAD

**Issue by Kamilkime** [CoolLord22/OtherDrops#97]
In the [last question of FAQ](https://github.com/CoolLord22/OtherDrops/wiki/Frequently-Asked-Questions-(FAQ)#q-can-i-use-enchantments-on-my-tooldropped-items) there's no exclamation sign between @ sign after item id and first enchantment name. From my tests - that sign is actually needed for the config to be read correctly.

So instead of:
`ITEM_ID@ENCHANTMENT1#LEVEL!ENCHANTMENT2#LEVEL!~CustomNameData`

There should be:
`ITEM_ID@!ENCHANTMENT1#LEVEL!ENCHANTMENT2#LEVEL!~CustomNameData`

**Comment by CoolLord22** [comment]
Many times, when using tools for example, the plugin will parse the ! into the enchantment name as well; it’s not a misdocumentation, it’s intentionally done that way as for tools if you include the first ! it will read !unbreaking for example as an enchantment when it really should be unbreaking. 

I’ll make sure to add a note saying to try both with and without the ! so we reduce the number of questions people have with it :)

**Comment by Kamilkime** [comment]
Yeah, in my case:
`gold_nugget@!unbreaking#10!~&6Coin` is the correct notation for the dropped item, not as the wiki would suggest - `gold_nugget@unbreaking#10!~&6Coin`

**Comment by CoolLord22** [comment]
As mentioned on Discord, if you ever have trouble figuring out how to configure an item within the plugin, you can always hold the item you wish to drop/have as a tool, run the command `/od write` and then verify that configuration is correct with `/od drop <config>` the config can then be put into the drops file without any problems.

**Comment by CoolLord22** [comment]
Corrected wiki
